app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin, current_user
from . import login_manager
from datetime import datetime
from sqlalchemy import text


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class ProfilePhoto(db.Model):
    __tablename__ = 'profile_photos'

    id = db.Column(db.Integer,primary_key = True)
    pic_path = db.Column(db.String())
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    photos = db.relationship('ProfilePhoto', backref = 'user', lazy = "dynamic")   


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)
    

    def __repr__(self):
        return f'User {self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")


    def __repr__(self):
        return f'User {self.name}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail, Message
from werkzeug.utils import secure_filename
from werkzeug.datastructures import  FileStorage
from flask_simplemde import SimpleMDE


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors

app/main/views.py
from flask import render_template, request, redirect, url_for,abort
from app.main import main
from flask_login import login_required, current_user
from .. import db,photos
from app.models import User, ProfilePhoto
from .forms import UpdateProfile

@main.route('/')
def index():

    title = 'Welcome to black origin'
    return render_template('index.html', title = title)

# @main.route('/contacts')
# def contact():
       
#     title = 'Black origin Contacts'
#     return render_template('contacts.html', title = title)

# @main.route('/about')
# def about():
       
#     title = 'Black origin about page'
#     return render_template('about.html', title = title)


@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("index.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data
        
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()

    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.index',uname=uname))

app/templates/about.html
<!-- {% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{%block styles%}
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Montserrat&family=Permanent+Marker&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
            integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">


        {%endblock%}

{% block content %}


<div class="container">
    <div class="row">
      <div class="col-md-4">
        <h1
          style="font-style:  italic; font-weight: bold; font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif; text-align: center;">
          BLVCK ORIGIN</h1>
        <img src="{{url_for('static',filename='photos/sty3/IMG-20201230-WA0013.jpg')}}" class="d-block w-100" alt="...">
        <small><i>The best Urban Wear and photography accross Nairobi and East Africa at large</i></small>
      </div>
      <div class="col-md-8">
        <marquee behavior="scall" direction="right"><h2
          style="color: rgb(19, 15, 15);text-align: center; padding-top: 30px;font-weight: 900; padding-bottom: 30px; font-style: italic;">
          ABOUT BLVCK ORIGIN</h2></marquee>
        <p style="color: rgb(14, 15, 15);"> We are family and event portrate photographers residing in Nairobi ,Kenya. Besides being best in photography we also sell outfits that may sort your preference.
            e believe that as your portrait photographer, we know there is so much than delivering beautiful images. It's about telling your story. It's about capturing that amaizing giggle and that smile from your
            little ones. And most importantly the genuine connection you have between your love ones. We strive in creating beautiful images and creating lasting memories for you and your family.
            </p>
            <h2
          style="color: rgb(19, 15, 15);text-align: center; padding-top: 30px;font-weight: 900; padding-bottom: 30px; font-style: italic;">
          SKILLS</h2>

      </div>
    </div>
  </div>



{% endblock%} -->

app/templates/base.html
<html>

<head>

</head>

<body style="background-color: lightblue;">
    <div>
        {% extends 'bootstrap/base.html'%}
        {% import 'bootstrap/wtf.html' as wtf %}

        <!-- Navbar block  -->
        {% block navbar %}
        {% include 'navbar.html' %}
        {% endblock %}

        <!-- Content block -->

        <meta charset="utf-8">
        <title> </title>
        {% block styles%}
{{ super() }}
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Dancing+Script=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href='https://fonts.googleapis.com/css?family=Carter+One&display=swap' rel="stylesheet">
      <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css')}}" />

{% endblock %}

        {% block content %}

        {% endblock%}
    </div>

</body>

</html>

app/templates/contacts.html
<!-- {% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{%block styles%}
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Montserrat&family=Permanent+Marker&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
            integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">


        {%endblock%}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h1
                style="font-style:  italic; text-align: center; font-weight: bold; font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;">
                BLVCK ORIGIN</h1>
            <img src="{{url_for('static',filename='photos/logo/IMG-20201230-WA0044.jpg')}}" class="d-block w-100"
                alt="..." height="300px">
            <small><i>The best Urban Wear and photography accross Nairobi and East Africa at large</i></small>
        </div>
        <div class="col-md-8">
            <marquee behavior="scall" direction="right"><h2
                style="color: rgb(19, 15, 15);text-align: center; padding-top: 30px;font-weight: 900; padding-bottom: 30px; font-style: italic;">
                CONTACT INFORMATION</h2></marquee>
            <p style="color: rgb(14, 15, 15);"> You can find us through the following links and contact information:</p>
            <ol>
                <li>Our shop and studio are located in mama ngina street, mutwathi lane. </br> Afya house, third floor
                    room 26.</li>
                <br>
                <li><b>Tel No:</b> <i>0719640643 or 0712345678</i></li>
                <br>
                <li>You can follow us on :</li>
            </ol>

                <div class="text-center text-black" style="text-align: center; padding-top: 10px;">

                    <img src="{{url_for('static',filename='photos/social/pinterest.png')}}">
                    <small style="font-size: small;">blvck_origin</small>

                    <img src="{{url_for('static',filename='photos/social/twitter.png')}}">
                    <small style="font-size: small;"> @Blvckorigin</small>

                    <img src="{{url_for('static',filename='photos/social/instagram.png')}}" style="height: 40px; width: 40px;">
                    <small style="font-size: small;">_blvck_origin</small>
                </div>
        </div>
    </div>
</div>

{% endblock%} -->

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
<h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/index.css')}}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    {% if title %}
    <title>Photo_spy Website {{title}}</title>
    {% else %}
    <title>Photo_spy Website</title>
    {% endif %}
</head>

<body>




    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border border-2 border-green rounded-0" style="background-color: aqua;">
        <div class="container-fluid">
            <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="/"style="color: white; font-size: large; font-weight: 400;"><i class="fa fa-home" style="color: rgb(36, 214, 45);"></i> HOME</a>
            </li>
        </ul>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="nav navbar-nav navbar-right">
                    <hr>
                    <li>
                        <a href="#contact"style="color: white; font-size: large; font-weight: 400;"><i class="fas fa-envelope" style="color: rgb(36, 214, 45);"></i> Contact us</a>
                    </li>
                    <hr>
                    <hr>
                    <li>
                        <a href="#about"style="color: white; font-size: large; font-weight: 400;"><i class="person" style="font-size:48px;color: rgb(36, 214, 45);"></i> About Us</a>
                    </li>
                    <hr>
                    <li>
                        <a href="{{url_for('auth.logout')}}"style="color: white; font-size: large; font-weight: 400;"><span style="color: rgb(36, 214, 45)" class="glyphicon glyphicon-log-in mr-3"></span> Checkout</a>
                    </li>
                    <hr>
                    <li>
                        <a href="{{url_for('auth.login')}}"style="color: white; font-size: large; font-weight: 400;"><span style="color: rgb(36, 214, 45)" class="glyphicon glyphicon-log-in mr-3"></span> Login</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>


</body>

</html>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container" style="color: black;">
  <div class="row">

    <div class="col-md-2">

      {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}"
        style="color:black; font-size:30px; font-weight: bold;">Edit profile</a>
      {% endif %}
    </div>

    <!--Display profile photo-->

    <div class="col-md-7">
      {% if user.profile_pic_path %}

      <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

      {%else%}
      <p>No profile picture</p>

      {% endif %}

      {% if user == current_user %}
      <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">

        <input type="file" name="photo" class="form-control" required>
        <input type="submit">
      </form>
      {% endif %}
    </div>

    <!-- displaying  Username-->
    <div class="col-md-3">
      <h3 style="color: black; font-weight: bold; font-size: 30px;"> {{user.username| capitalize}} </h3>

      <!--Displaying user bio-->
      {% if user.bio %}
      <p> {{user.bio}}</p>
      {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
      {% endif %}
      {% if user.area %}
      <p> {{user.username}} Lives in {{user.area}}</p>
      {%else%}
      <p> {{user.username| capitalize}} has no location </p>
      {% endif %}
      {% if user.gender %}
      <p> is {{user.gender}} Gender</p>
      {%else%}
      <p> {{user.username}} {{user.username| capitalize}} has no gender </p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container" style="background: dimgray; color: black;">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}